### ISSUE TITLE
writeThreejsPage should accept a camera orientation

### ISSUE THREAD

**Issue by fischman** [jsxcad/JSxCAD#32]
writeThreejsPage should allow specifying a camera view vector in addition to cameraPosition to make the initial view look more 3Dish for axis-aligned designs.

**Comment by pentacular** [comment]
Wouldn't it be more convenient to give the camera an absolute point to look at instead of a relative direction to look in?

Then you can say, "look at my thing, from over there."

(Or is this what you're suggesting, and I've misunderstood?)

**Comment by fischman** [comment]
LookAt point is a great way to express what I want here.

**Comment by fischman** [comment]
Another option: compute the bounds of the geometry and always start by looking at the center of the bounds.

**Comment by pentacular** [comment]
Sounds good -- let's figure out lookAt and lookFrom.

And default it to lookAt the center, and lookFrom far enough away that the whole volume is visible. :)

**Comment by fischman** [comment]
Is your proposed lookFrom different to the existing cameraPosition?
Or just another name to make more sense in conjunction with lookAt?

**Comment by pentacular** [comment]
The view supports position and orientation.
