### ISSUE TITLE
main should support async

### ISSUE THREAD

**Issue by pentacular** [jsxcad/JSxCAD#45]
The main function of scripts should support async operations.

This will allow i/o operations (e.g., fetching ldraw files).
This will allow interactivity (e.g., have a loop which asks the user if they want to add another cube).
This will allow more flexible input processing.

**Comment by FishOrBear** [comment]
Using programming to generate entities is not cool enough, I think it's cool enough to be an interactive design tool like AutoCAD.

**Comment by pentacular** [comment]
I think there are things to be said for both approaches.

The main advantage of procedural generation is that it's repeatable and can be parametric, which allows for precise design.

The advantage of interactive tools is that they help with fitting things together until they feel right.

What I have been considering is support for a constraint resolving armature system, and I think that would make sense for an interactive style.

e.g., you build something like a skeleton and then clothe it with geometry.

**Comment by FishOrBear** [comment]
> I think there are things to be said for both approaches.
> 
> The main advantage of procedural generation is that it's repeatable and can be parametric, which allows for precise design.
> 
> The advantage of interactive tools is that they help with fitting things together until they feel right.
> 
> What I have been considering is support for a constraint resolving armature system, and I think that would make sense for an interactive style.
> 
> e.g., you build something like a skeleton and then clothe it with geometry.

Interactive editor + programmable plugin will solve the problem.

**Comment by pentacular** [comment]
Interactive editor + programmable plugin won't solve the problem, because it can mean almost anything, which makes it almost meaningless.

If you want to solve this problem, the first step is to clearly express the problem that you're trying to solve.

So, what problem is it that you want to solve? :)

The first question you'll need to answer is this -- what is the representation that you're operating on?
(a) Are you editing code that generates geometry? or
(b) Are you editing geometry using code?

This project is aligned with (a) rather than (b).
So if you're after (b) then it may not be a good fit. :)

If you're interested in (a), then you'll need to think about how using the mouse can fit into code generation.

**Comment by pentacular** [comment]
Main supports async. :)
