### ISSUE TITLE
Layout function

### ISSUE THREAD

**Issue by BarbourSmith** [jsxcad/JSxCAD#83]
I think it could be very cool to have a function which took an assembly as an argument and created a laid out version ready to laser cut. 

I have found myself spending a lot of time laying out files to cut for laser cutting after adjusting one parameter in the model which can be a huge time sync for iterative design. 

Most of the building blocks are already in place. We can export parts to svg and this library can do the packing https://github.com/Jack000/SVGnest . We may need to add a layFlat function similar to what jscad has.

**Comment by pentacular** [comment]
Yes, that's one of the main reasons for having assemblies. :)

But it's not just laser cutting -- it's a general fabrication requirement.
You'll often want to print in a different orientation to that of assembly.

Having taken a look at SVGnest, I see a couple of obstacles.

(a) It's not structured for use as a library module.
(b) It's tied into the browser DOM model for some reason.
(c) It's tied into running on the browser generally, and looks hard to extract from that.

So I don't think it's going to be workable to turn everything into svg and then just calling SVGnest.

Which leaves three general strategies:
  (d) extract the useful parts and credit the original authors, or
  (e) fork-and-refactor with the expectation of reintegrating later, or
  (f) build a new system, taking advantage of the high level concept and design.

I don't know what's most appropriate approach, but I agree this is a problem that should be tackled. :)

**Comment by pentacular** [comment]
FFR:

http://www.graham-kendall.com/papers/k2001.pdf
https://www.sciencedirect.com/science/article/pii/S0305054806000669
http://www.cs.stir.ac.uk/~goc/papers/EffectiveHueristic2DAOR2013.pdf
https://www.sciencedirect.com/science/article/abs/pii/S0377221706001639
https://www.sciencedirect.com/science/article/pii/S0305054804003053
http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.62.4891&rep=rep1&type=pdf

**Comment by pentacular** [comment]
simple pack function implemented
